# Generated by Django 4.2.2 on 2024-08-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("email",),
                "permissions": [
                    ("can_view_users_list", "can view users list"),
                    ("can_block_user", "can block user"),
                ],
                "verbose_name": "Юзер",
                "verbose_name_plural": "Юзеры",
            },
        ),
    ]
