# Generated by Django 4.2.2 on 2024-08-29 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        default="media_default/blog_img.png", upload_to="blog_images/"
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "publish_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": ["-publish_date"],
                "permissions": [
                    ("can_create_blogpost", "can view blogpost"),
                    ("can_update_blogpost", "can update blogpost"),
                    ("can_delete_blogpost", "can delete blogpost"),
                ],
            },
        ),
    ]
