# Generated by Django 4.2.2 on 2024-08-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                default="static/media_default/blog_img.png",
                upload_to="blog_images/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Заголовок"),
        ),
    ]
