# Generated by Django 4.2.2 on 2024-08-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_content_alter_blog_image_alter_blog_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                default="media_default/blog_img.png",
                upload_to="blog_images/",
                verbose_name="Изображение",
            ),
        ),
    ]
