# Generated by Django 4.2.2 on 2024-08-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog_images/",
                verbose_name="Изображение",
            ),
        ),
    ]
