# Generated by Django 4.2.2 on 2024-08-25 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="email",
            field=models.ManyToManyField(
                related_name="emails", to="main.client", verbose_name="Клиент с почтой"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="interval",
            field=models.CharField(
                choices=[
                    ("once a minute", "once a minute"),
                    ("once a day", "once a days"),
                    ("once a week", "once a week"),
                    ("once a month", "once a months"),
                ],
                default="once a week",
                verbose_name="Интервал",
            ),
        ),
    ]
