# Generated by Django 4.2.2 on 2024-08-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_mailing_user_alter_mailing_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="auto_start",
            field=models.BooleanField(
                default=False, verbose_name="Автоматический старт"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания рассылки"
            ),
        ),
    ]
