# Generated by Django 4.2.2 on 2024-08-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_mailing_auto_start_mailing_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="send_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата начала рассылки"
            ),
        ),
    ]
