# Generated by Django 4.2.2 on 2024-08-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_client_users_remove_mailing_email_client_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ("interval",),
                "permissions": [
                    ("can_change_mailing", "can change mailing"),
                    ("can_delete_mailing", "can delete mailing"),
                    ("can_view_mailing", "can view mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="trymailing",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="main.mailing",
                verbose_name="Рассылка",
            ),
        ),
    ]
