# Generated by Django 4.2.2 on 2024-08-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_mailing_options_alter_mailing_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("email",),
                "permissions": [
                    ("can_view_сlients", "can view сlients"),
                    ("can_change_сlients", "can change сlients"),
                    ("can_delete_сlients", "can delete сlients"),
                ],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
