# Generated by Django 4.2.2 on 2024-08-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_client_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("email",),
                "permissions": [
                    ("can_view_clients", "can view clients"),
                    ("can_change_clients", "can change clients"),
                    ("can_delete_clients", "can delete clients"),
                ],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ("subject",),
                "permissions": [
                    ("can_change_message", "can change message"),
                    ("can_delete_message", "can delete message"),
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
