# Generated by Django 4.2.2 on 2024-08-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_client_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ("interval",),
                "permissions": [
                    ("can_change_mailing", "can change mailing"),
                    ("can_delete_mailing", "can delete mailing"),
                    ("can_view_mailing", "can view mailing"),
                    ("can_create_mailing", "can create mailing"),
                    ("can_switch_mailing", "can switch mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
